service:
  name: imprint-github
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    GITHUB_API_KEY: ${env:GITHUB_API_KEY}

functions:
  getUserRepositories:
    handler: src/handlers/user.getRepositories
    events:
      - http:
          method: get
          path: user/{login}/repos
          cors: true
  getUserImprint:
    handler: src/handlers/user.getUserImprint
    events:
      - http:
          method: get
          path: user/{login}/imprint
          cors: true
  getOrgStatContribution:
    handler: src/handlers/repo.getOrgStatContribution
    events:
      - http:
          method: get
          path: org/{organisation}/stats
          cors: true
