name: backend-github-validate

on:
  push:
    paths:
      - backend/github/**
      - .github/workflows/backend-github-validate.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Validate
      env:
        GITHUB_API_KEY: ${{ secrets.GITHUB_API_KEY }}
      working-directory: ./backend/github
      run: |
        npm ci
        npm run test
