name: Deploy github backend

on:
  push:
    paths:
      - backend/github/**
    branches:
      - master
      - Deploy-github-backend

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm install
      uses: actions/npm@master
      with:
        args: install
    - name: serverless deploy
      uses: serverless/github-action@v1.53.0
      with:
        args: deploy --stage=prod --region=eu-central-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.BACKEND_GITHUB_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.BACKEND_GITHUB_AWS_SECRET_ACCESS_KEY }}
