name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Validate
      env:
        GITHUB_API_KEY: ${{ secrets.GITHUB_API_KEY }}
        test_env:  ${{ secrets.aaa }}
      working-directory: ./backend/github
      run: |
        echo $test_env
        npm ci
        npm run test
