name: web-validate

on:
  push:
    paths:
      - web/**
      - .github/workflows/web-validate.yml

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Validate
      working-directory: ./web
      run: |
        npm install -g @angular/cli
        npm ci
        ng test --watch=false --browsers=ChromeHeadless
        ng lint
        ng build --prod
