name: web-deploy

on:
  push:
    branches:
    - master
    paths:
      - web/**
      - .github/workflows/web-deploy.yml
jobs:
  web-deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Npm ci & build
      working-directory: ./web
      run: |
        npm ci
        npm run build:prod

    - uses: w9jds/firebase-action@v1.3.0
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_PATH: ./web
