name: web-deploy

on:
  push:
    branches:
    - master
    - webdeploy

jobs:
  web-deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Npm ci & build
      working-directory: ./web
    - run: | 
        npm ci
        npm run build:prod

    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_PATH: ./web
